[package]
name = "siege-mesh"
version = "0.1.0-unstable11"
authors = ["Mike Dilger <mike@optcomp.nz>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "0.9"
siege-math = { path = "../siege-math" }
