[package]
name = "siege-mesh"
version = "0.4.0-unstable"
authors = ["Mike Dilger <mike@optcomp.nz>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
bincode = "0.9"
siege-math = { git = "ssh://mike@git.gnomonicgames.com/data/git/siege-math.git", branch="0.3" }
error-chain = "0.11"
